# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpnIVbZn34DITehey_OUuRJq63f6zz2H
"""

def existe_contato(lista, email):

  if len(lista) > 0:
      for contato in lista:
        if contato['email'] == email:
          return True
      return False 

def adicionar(lista):
  
  while True:
    email = input("Digite o e-mail do contato: ")

    if not existe_contato(lista, email):
        break
    else:
      print("Esse e-mail já foi utilizado.")
      print("Por favor, tente um novo e-mail")

  contato = {
        "email": email,
        "nome": input("Digite o nome"),
        "tel": input("Digite o telefone")
    }

  lista.append(contato)

  print("O contato {} foi cadastrado com sucesso!\n" . format(contato['nome']))  



def alterar():
  pass

def excluir():
  pass

def buscar():
  pass

def listar(lista):
    print("== Listar Contatos ==")
    if len(lista) > 0:
        for i, contato in enumerate(lista):
            print("Contato {}:".format(i+1))
            print("\tNome: {}".format(contato['nome']))
            print("\tEmail: {}".format(contato['email']))
            print("\tTelefone: {}".format(contato["tel"]))
            print("===========================================")

        print("Quantidade de contatos: {}\n".format(len(lista)))

    else:
      print("Não existe nenhum contato cadastrado no sistema.\n")       

  

def principal():

    lista = []

    while True:    
        print(" === Agenda Telefonica ===")
        print(" 1 - Adcionar contato ")
        print(" 2 - Alterar contato ")
        print(" 3 - Excluir contato ")
        print(" 4 - Buscar contato ")
        print(" 5 - Listar contato ")
        print(" 6 - Sair ")
        opção = int(input("> "))

        if opção == 1:
          adicionar(lista)
        elif opção == 2:
          alterar()
        elif opção == 3:
          excluir()
        elif opção == 4:
          buscar()
        elif opção == 5:
          listar(lista)
        elif opção == 6:
          print("Saindo do programa...")
          break
        else:
          print("Opção inválida. Por favor, tente novamente")

principal()

