# -*- coding: utf-8 -*-
"""LogicadeProgramacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eZTLpsG8p0v6umUBdri58xX47FeCyOgX

# **Logica de Progamacao**
"""

1+1

'Guilherme'



"""Minha Primeira funcao 

"""

def saudacao():
  nome = input ('Qual o seu nome ?')
  print(f'Olá{nome}')

saudacao()

