# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpnIVbZn34DITehey_OUuRJq63f6zz2H
"""

def principal():

  print(" === Agenda Telefonica ===")
  print(" 1 - Adcionar contato ")
  print(" 2 - Alterar contato ")
  print(" 3 - Excluir contato ")
  print(" 4 - Buscar contato ")
  print(" 5 - Listar contato ")
  print(" 6 - Sair ")
  opção = int(<))